[LegalNotice]
Accepted=true

[BitTorrent]
Session\Port=51420
Session\DHTEnabled=true
Session\PeXEnabled=false
Session\LSDEnabled=false
Session\QueueingSystemEnabled=false
Session\AddTorrentStopped=true
Session\DefaultSavePath=/tmp
Session\TempPathEnabled=false
Session\GlobalMaxRatio=0
Session\GlobalMaxSeedingMinutes=0

[Preferences]
WebUI\Enabled=true
WebUI\Address=*
WebUI\Port=8080
WebUI\LocalHostAuth=false
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\AuthSubnetWhitelist=172.30.0.5/32, fd00:cafe:2::5/128
WebUI\HostHeaderValidation=false
WebUI\CSRFProtection=false
